### ISSUE TITLE
Initial upload nicht möglich

### ISSUE THREAD

**Issue by Dave2526** [SteMaker/wortuhr#16]
Hallo, ich versuche gerade den Intitial Upload zu starten, jedoch kommt immer die unten gezeigt Fehlermeldung. Ich finde lieder keine brauchbare Hilfe dieses Problem zu lösen...

 *  Task wird ausgeführt: C:\Users\User\.platformio\penv\Scripts\platformio.exe run --target upload --environment inital_upload 

Processing inital_upload (platform: espressif8266@^2; board: esp12e; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp12e.html
PLATFORM: Espressif 8266 (2.7.4+9) > Espressif ESP8266 ESP-12E
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 2.7.4+9
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30300.220323 (3.3.0)
 - tool-mklittlefs @ 1.203.200522 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 38 compatible libraries
Scanning dependencies...
Dependency Graph
|-- NTPClient @ 3.2.1+sha.78d4237
|-- FastLED @ 3.5.0+sha.0838804
|   |-- SPI @ 1.0
|   |-- EspSoftwareSerial @ 6.10.0
|-- ESP Async WebServer @ 1.2.3+sha.f71e3d4
|   |-- ESPAsyncTCP @ 1.2.2
|   |   |-- ESP8266WiFi @ 1.0
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- ESP_EEPROM @ 2.1.2+sha.63796bc
|-- CRCx @ 0.3.2+sha.ccaab2a
|-- BH1750FVI @ 1.1.1+sha.1e18959
|   |-- Wire @ 1.0
|-- TSL2561 Arduino Library @ 1.0.0+sha.fea818e
|   |-- Wire @ 1.0
|-- ArduinoJson
|-- ESP8266WiFi @ 1.0
|-- ESPAsyncTCP @ 1.2.2
|   |-- ESP8266WiFi @ 1.0
|-- Wire @ 1.0
|-- ArduinoOTA @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266mDNS @ 1.2
|   |   |-- ESP8266WiFi @ 1.0
Building in release mode
Compiling .pio\build\inital_upload\src\main.cpp.o
Compiling .pio\build\inital_upload\lib45a\SoftwareSerial\SoftwareSerial.cpp.o
Compiling .pio\build\inital_upload\libd78\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Compiling .pio\build\inital_upload\libd78\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\inital_upload\libd78\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\inital_upload\libd78\ESP8266WiFi\WiFiClientSecureAxTLS.cpp.o
Compiling .pio\build\inital_upload\libd78\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\inital_upload\libd78\ESP8266WiFi\WiFiServer.cpp.o
src\main.cpp:2:25: fatal error: ArduinoJson.h: No such file or directory

*********************************************************************
* Looking for ArduinoJson.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ArduinoJson.h"
* Web  > https://registry.platformio.org/search?q=header:ArduinoJson.h
*
*********************************************************************

 #include <ArduinoJson.h>
                         ^
compilation terminated.
*** [.pio\build\inital_upload\src\main.cpp.o] Error 1
In file included from C:\Users\User\.platformio\packages\framework-arduinoespressif8266@2.7.4+9\libraries\SoftwareSerial\src\SoftwareSerial.cpp:23:0:
C:\Users\User\.platformio\packages\framework-arduinoespressif8266@2.7.4+9\libraries\SoftwareSerial\src\SoftwareSerial.h:132:9: error: 'int SoftwareSerial::availableForWrite()' marked override, but does not override
     int availableForWrite() override {
         ^
*** [.pio\build\inital_upload\lib45a\SoftwareSerial\SoftwareSerial.cpp.o] Error 1
======================================================================== [FAILED] Took 6.10 seconds ========================================================================

Environment    Status    Duration
-------------  --------  ------------
inital_upload  FAILED    00:00:06.098

**Comment by stan23** [comment]
Aus irgendeinem Grund hat PlatformIO nicht die Lib "ArduinoJson" installiert.

Kannst du zum Test die Zeile https://github.com/SteMaker/wortuhr/blob/master/fw/platformio.ini#L28 durch "bblanchon/ArduinoJson" ersetzen?
Wenn das nicht hilft, dann direkt in PlatformIO diese Lib installieren?

Den zweiten Fehler ("override") verstehe ich momentan nicht.

**Comment by Dave2526** [comment]
AdrduinoJson Fehler ist weg, der andere allerdings noch da...

**Comment by Dave2526** [comment]
Hab jetzt einfach mal unter C:\Users\User\.platformio\packages\framework-arduinoespressif8266@2.7.4+9\libraries\ den SoftwareSerial gelöscht, jetzt gehts... 
Schließe hiermit den Issue, Vielen Dank für die Hilfe!
